Repository milieuinfo/webcomponenten-vl-ui-bom, pull requests merged in 2020-10, with the labels that each got.

#5 Update dependency copyfiles to v2.4.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#6 Introductie vl-ui-document en vl-ui-info-tile en update dependencies
  package-lock.json
  package.json
Labels: enhancement

#7 Update util
  test/docker-compose.yml
  test/e2e-results.xml
Labels: chore

#8 Update util
  .gitignore
  bamboo-specs/bamboo.yml
  test/e2e-results.xml
Labels: chore

#9 Schakel over op multireporter
  .mocharc.js
  package-lock.json
  package.json
  reporter-config.json
Labels: chore

#10 Update docker-compose
  test/docker-compose.yml
Labels: chore
