Repository milieuinfo/webcomponenten-vl-ui-bom, pull requests merged in 2021-01, with the labels that each got.

#16 Introductie vl-ui-accessibility, vl-ui-contact-carad, vl-ui-cookie-statement, vl-ui-privacy en vl-ui-side-navigation
  package-lock.json
  package.json
Labels: enhancement

#17 Extra demo pagina's CSS import automatisch aanpassen
  .mocharc.js
  package-lock.json
  scripts/copy-styles.js
Labels: chore

#18 Update dependencies
  .gitignore
  .mocharc.js
  package-lock.json
  package.json
Labels: chore

#19 Update dependencies en introductie gebruik van vaste versies
  package-lock.json
  package.json
Labels: chore

#20 Update dependency vl-ui-core to v7.0.3
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#21 Update dependency vl-ui-datepicker to v3.2.4
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#22 Update dependency vl-ui-map to v5.1.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#23 Update dependency vl-ui-button to v5.0.9
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#24 Update dependency vl-ui-core to v7.1.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#25 Update dependency vl-ui-util to v5.3.7
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
