Repository milieuinfo/webcomponenten-vl-ui-bom, pull requests merged in 2021-04, with the labels that each got.

#68 Update dependency vl-ui-accordion to v3.1.1
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#67 Update dependencies en introductie vl-ui-tabs dependency
  .mocharc.js
  package-lock.json
  package.json
Labels: enhancement

#69 Update dependencies
  package-lock.json
  package.json
Labels: chore

#70 Update dependency vl-ui-core to v7.2.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#71 Update dependency vl-ui-proza-message to v1.1.6
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#72 Update dependency vl-ui-upload to v3.6.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#74 Update dependency vl-ui-accordion to v3.1.3
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#75 Update dependency vl-ui-info-tile to v1.1.3
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#76 Update dependency vl-ui-search-filter to v3.3.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#77 Update dependency vl-ui-select to v4.3.0
  package-lock.json
  package.json
Labels: chore, dependencies, renovate

#78 Update dependency vl-ui-tabs to v1.0.2
  package-lock.json
  package.json
Labels: chore, dependencies, renovate
